### ISSUE TITLE
How to run watir in GitHub actions

### ISSUE THREAD

**Issue by specter78** [watir/watir#937]
Not able to initialize browser itself.

**Comment by titusfortner** [comment]
You can look at the code in this repo to see how we do it: https://github.com/watir/watir/tree/main/.github

Let us know if you have additional questions or a reproducible issue we can investigate.

**Comment by specter78** [comment]
> You can look at the code in this repo to see how we do it: https://github.com/watir/watir/tree/main/.github

Based on this, I created the following workflow file:

```yml
name: workflow

on:
  push:
  workflow_dispatch:

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Setup Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -qqy
        sudo apt-get -qqy install google-chrome-stable
        sudo rm /etc/apt/sources.list.d/google-chrome.list

    - name: Run Script
      run: |
        bundle
        ruby script.rb
```

Finally, on running `browser = Watir::Browser.new` I get the following error:
```#0 0x56415393b949 <unknown>: unknown error: Chrome failed to start: exited abnormally. (Selenium::WebDriver::Error::UnknownError)
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)```
